#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "[Wind Turbine Sample App] PR workflow"
run-name: "[Wind Turbine Sample App] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  pull_request:
    paths:
      - 'manufacturing-ai-suite/wind-turbine-anomaly-detection/*'
  workflow_call:
  workflow_dispatch:
permissions: {}

jobs:
  windturbine-sample-app-pre-merge-build:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
    - name: Runner workspace path
      run: |
        echo "Cleaning up previous run"
        if [ -n "$(docker ps -aq)" ]; then
            docker stop $(docker ps -aq)
        fi
        if [ -n "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
        fi
        docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
    - uses: actions/checkout@v1
      with:
          path: timeseries
    - name: Build
      run: |
        cd ./manufacturing-ai-suite/wind-turbine-anomaly-detection
        make build
    - name: Deploy
      run: |
        cd "${{ github.workspace }}"
        cd ./manufacturing-ai-suite/wind-turbine-anomaly-detection
        echo "Deploying Wind Turbine Anomaly Detection Sample App"
        
    - name: Undeploy
      run: |
        cd "${{ github.workspace }}"
        cd ./manufacturing-ai-suite/wind-turbine-anomaly-detection
        make down